# Generated by Django 5.2.14 on 2026-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_suggestion_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
